### ISSUE TITLE
persistentFileRollingInterval only works when rollOnFileSizeLimit: false

### ISSUE THREAD

**Issue by Oliviaophia** [dfacto-lab/serilog-sinks-file#12]
Hello,

> Specifying both `rollingInterval` and `rollOnFileSizeLimit` will cause both policies to be applied.

It seems that this feature does not take effect.
This is my configuration:
```
.WriteTo.PersistentFile(
"Info.log",
fileSizeLimitBytes: 100000,
rollOnFileSizeLimit: true,
shared: true,
persistentFileRollingInterval: PersistentFileRollingInterval.Day,
flushToDiskInterval: TimeSpan.FromSeconds(1)))
```

I found `persistentFileRollingInterval` only works when `rollOnFileSizeLimit: false`.
`rollOnFileSizeLimit: true` always works, regardless of whether `persistentFileRollingInterval` is configured.

**Comment by numito** [comment]
Hi,

Both settings are exclusive. You would like to have both active at the same time. What’s you use case ?

Numa

**Comment by numito** [comment]
No response so closing this issue
