### ISSUE TITLE
Starts empty at start

### ISSUE THREAD

**Issue by KoalaBear84** [dfacto-lab/serilog-sinks-file#4]
Thanks for putting up the Nuget.

Every time I start the application, the log will start over completely. So all history is gone, before the file is rolled.

That is dangerous. Can this be prevented?

**Comment by numito** [comment]
Let met have a look, normally it should roll the file if it already exists.

**Comment by KoalaBear84** [comment]
Aha.. I see. Already had 5. I would be nice if it could be merged, but I definitely understand all the problems that come with that! So it's OK.

MyLogFile20201022.log
MyLogFile20201022_001.log
MyLogFile20201022_002.log
MyLogFile20201022_003.log
MyLogFile20201022_004.log
MyLogFile20201022_005.log

**Comment by numito** [comment]
Yes every time you start the program it will roll the file and start new, until the retain count is reached. 
Normally all data should be there and no data should be lost.

**Comment by KoalaBear84** [comment]
OK, thanks for the info.
