### ISSUE TITLE
Incompatible with Serilog.AspNetCore

### ISSUE THREAD

**Issue by KoalaBear84** [dfacto-lab/serilog-sinks-file#5]
Probably impossible to fix I guess? But at least it is 'documented'.

When adding Serilog.AspNetCore, which also depends on Serilog.Sinks.File it will give this error, and cannot solve because the namespaces are the same.

`The type 'RollingInterval' exists in both 'Serilog.Sinks.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' and 'Serilog.Sinks.PersistentFile, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'`

Example:
![image](https://user-images.githubusercontent.com/5886900/96862185-6a251680-1465-11eb-95cd-fa7e483838bf.png)

**Comment by numito** [comment]
This is tricky, you need to remove the reference to Serilog.Sinks.File, so there is no clash. Maybe this helps: https://stackoverflow.com/questions/52207524/disable-transitive-packagereference-dependency-for-a-specific-msbuild-project

**Comment by numito** [comment]
You can request https://github.com/serilog/serilog-aspnetcore/commits?author=nblumhardt <https://github.com/serilog/serilog-aspnetcore/commits?author=nblumhardt> , what you can do about this transitive dependency, he is the original author of the package. 
Another option would be to refactor my code to remove all duplicate code, between my package and his and rely on his Enumeration. I will have a look into that. I will keep you updated if I have found a better option. 


  <http://www.dfacto.ch/>	Numa Schmeder    www.dfacto.ch  <http://www.dfacto.ch/>
NUMA@DFACTO.CH <mailto:numa@dfacto.ch>   |   M +41 79 538 30 01 

DIGITAL STRATEGY   |   DESIGN   |   DEVELOPMENT

**Comment by KoalaBear84** [comment]
Hmm, that indeed seems to work! I'm not sure if this one is too 'rough', but at least it works.

```xml
  <Target Name="FixSerilogAspNetCoreIncompatibility" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'Serilog.Sinks.File'">
        <Aliases>nonmerged</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

**Comment by nblumhardt** [comment]
I think the usual way to deal with this is to rename the types involved; it might make sense to rename the configuration method and base any other renames on that:

```csharp
    .WriteTo.PersistenFile(..., PersistentFileRollingOptions.Day, ...)
```

**Comment by MichaRotstein** [comment]
any news on that ? I also think @nblumhardt suggestion above (`.WriteTo.PersistenFile`) is the best way to go

**Comment by numito** [comment]
> any news on that ? I also think @nblumhardt suggestion above (`.WriteTo.PersistenFile`) is the best way to go

It has been done already, this issue should be closed.

**Comment by MichaRotstein** [comment]
@numito I'm confused, do you mean it just works now out of the box with .aspnetcore or do I need to do something for that ?

**Comment by numito** [comment]
It works out of the box, just get the nugget and install it 


  <http://www.dfacto.ch/>	Numa Schmeder    www.dfacto.ch  <http://www.dfacto.ch/>
NUMA@DFACTO.CH <mailto:numa@dfacto.ch>   |   M +41 79 538 30 01 

DIGITAL STRATEGY   |   DESIGN   |   DEVELOPMENT
