### ISSUE TITLE
Static log files when rolling

### ISSUE THREAD

**Issue by PatriQ94** [dfacto-lab/serilog-sinks-file#6]
Hi, so I'm migrating an ASP.NET Framework web app to .Net Core. Currently we've been using Log4Net for logging, which has out of the box implemented rolling on file size with _static files_.

So for example it creates
log.txt
log.1.txt
log.2.txt
The latest logs are always found in the main log.txt, while the other two files are used to dump older logs. Once all 3 files are created, they're kept statically and only the content changes. No further files are created.

Now, Serilog also supports rolling on file size, but the only issue is is that these files are created _dynamically_, which require IIS to have _write_ permissions on the entire Logs folder. This is a security concern as we would like to have under control which files have which permissions. Is it possible to perhaps configure Serilog to work in a similar way?

**Comment by numito** [comment]
Hi,

This version of serialog file sink, works the way you describe. It’s a fork that adds the functionality of persistent file, just give it a try, it’s available on nuget.org
You would configure logs on file size with a maximum of 3 rolling logs.

**Comment by PatriQ94** [comment]
Intereting!

So you're saying that basically, I can pre-create logs for example:
log.txt
log_001.txt
log_002.txt
Then add them write permissions for IIS user, and Serilog would automatically take care of all the rest?

I've currently got an appsettings.json that looks like this:
```json

"Serilog": {
  "Using": [],
  "MinimumLevel": {
    "Default": "Information",
    "Override": {
      "Microsoft": "Warning",
      "System": "Warning"
    }
  },
  "Enrich": [],
  "WriteTo": [
    { "Name": "Console" },
    {
      "Name": "File",
      "Args": {
        "path": "Logs\\log.cshtml",
        "outputTemplate": "{Timestamp:dd/MM/yyyy HH:mm:ss} [{Level:u3}] {Message}{NewLine:1}{Exception:1}",
        "fileSizeLimitBytes": 10485760,
        "rollOnFileSizeLimit": true,
        "retainedFileCountLimit": 3,
        "shared": true
      }
    }
  ]
}
```

What would I have to change in this config for it to work the way you're describing?

**Comment by PatriQ94** [comment]
Okay so I've tested it, it works well, but not according to our needs. The backup logs (log_001.cshtml, log_002.cshtml etc.) are still being created _dynamically_, with incremental numbers in filenames, which would still require IIS having write permissions on the entire Folder so the app can even create these files, while we would need _all files being static_, without creation/removal, just content copying.

**Comment by numito** [comment]
Hi,

This could be changed quite easily. You can have a look at the code, instead of recreating file, you could just purge them and write in the same file. 
I am not sure it’s the best security measure you can have, I don’t understand the benefits of doing such a measure.  
You should create a folder in your log folder with appropriate permissions, and set the retention count to 3 with a maximum file size. You guarantee that no other file will get ever written somewhere else and you isolate your risk inside a folder, it’s a safer security measure. 

Numa

**Comment by PatriQ94** [comment]
> I don’t understand the benefits of doing such a measure.

I guess the reasoning is is that such measures gives more control which folders and files have which permissions in a production environment.

> You can have a look at the code, instead of recreating file, you could just purge them and write in the same file.

How would I go about doing this? I've never before edited some nuggets source code and then integrated the changed thing.
