### ISSUE TITLE
File rolling on application restart even if FileSizeLimit not yet reached

### ISSUE THREAD

**Issue by DavidErben** [dfacto-lab/serilog-sinks-file#7]
Hello,

first of all thanks for this project, it is really helpful and exactly what I needed. I have found a small issue where I am not sure if this is intended behavior. Consider the following configuration:

> Log.Logger = new LoggerConfiguration()
      .WriteTo.Async(c => c.PersistentFile(logFilePath,
          retainedFileCountLimit: 5,
          rollOnFileSizeLimit: true,
          preserveLogFilename: true,
          fileSizeLimitBytes: 131072,
          persistentFileRollingInterval: PersistentFileRollingInterval.Infinite))
      .CreateLogger();

Expected behavior is that the log filename is preserved and the logfile is rolled when it exceeds the configured file size of 128kB. But if I restart my application, a new logfile is created even if the file size limit has not been reached yet. I would have expected that in this case the logger keeps writing into the same file on application restart, because the file size limit is not yet reached.

Is this a misunderstanding from my side or a bug? The affected code is the following:

RollingFileSink.cs line 180
`if (System.IO.File.Exists(currentPath) && new FileInfo(currentPath).Length > 0)`

What I would expect is something like:
`if (System.IO.File.Exists(currentPath) && (_rollOnFileSizeLimit ? new FileInfo(currentPath).Length >= _fileSizeLimitBytes : new FileInfo(currentPath).Length > 0))`

What are your thoughts on this? Thanks in advance!

**Comment by numito** [comment]
Hi, 

Yes you are actually write this would avoid rolling files when we start stop application if we haven't reached the limit, and if we have roll on on file size limit enabled. 

I will implement the change and push a new release.

**Comment by DavidErben** [comment]
Great, thanks! Then I will wait for the new release.

**Comment by numito** [comment]
Change has been included in new release 4.1.0-beta2
