### ISSUE TITLE
Fixed file name for logging with rolling archive 

### ISSUE THREAD

**Issue by VhatAmI** [dfacto-lab/serilog-sinks-file#8]
"When logging rolls, all new entries are written to the rolled file. Can't this be changed so that logging keeps getting written to "sample.log" and the rolled files "sample001.log", "sample002.log", etc. keep the history?" -- from issue #40

Has this been implemented?

**Comment by numito** [comment]
This is the purpose of this fork !

Regards

Numa

**Comment by bartelink** [comment]
Perhaps its worth renaming this repo to e.g. `serilog-sinks-persistentfile` ??

**Comment by VhatAmI** [comment]
> Perhaps its worth renaming this repo to e.g. `serilog-sink-persistentfile` ??

Thanks, I got linked to this issue page from another issue on the main serilog repo and never actually made it to the Readme/landing page of the repo. Whoops! =-)
